#!/usr/bin/env python3
"""
convert-seed.py — turn firebase-seed.json (RTDB tree) into sql/seed.sql
(relational inserts matching sql/schema.sql).

Mapping (documented in docs/supabase/SCHEMA.md):
  solar.meta                → module_state 'solar/meta'
  solar.itcs.{id}           → solar_itcs.data (minus acts) + solar_activities rows
  wtg.meta                  → module_state 'wtg/meta'
  wtg.turbines.{id}         → wtg_turbines.data
  bop.acts / acts66         → bop_activities (33kv / 66kv), data = raw value
  bop.pss.acts / gss.acts   → bop_activities (pss / gss)
  bop.feeders33[i]          → bop_assets ('feeders33', str(i))
  bop.lines33 / poles33     → bop_assets ('lines33'/'poles33')  [if present]
  rowIssues.{-key}          → row_issues (legacy_id preserved)
  milestones.{-key}         → milestones (label→title, date→mdate)
  hse.observations.{-key}   → hse_observations (known keys → columns, rest → extra)
  hse.employees.{code}      → hse_employees

Anything else at the top level is preserved verbatim in module_state under
its original path so no data is silently dropped (printed as a warning).

Usage:  python3 tools/convert-seed.py [in.json] [out.sql]
"""
import json, sys, datetime

IN  = sys.argv[1] if len(sys.argv) > 1 else 'firebase-seed.json'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'sql/seed.sql'

def q(s):
    """SQL string literal."""
    if s is None: return 'null'
    return "'" + str(s).replace("'", "''") + "'"

def jq(o):
    """SQL jsonb literal."""
    return q(json.dumps(o, ensure_ascii=False)) + '::jsonb'

def num(v, default=0):
    try:
        f = float(v)
        return str(int(f)) if f == int(f) else str(f)
    except (TypeError, ValueError):
        return str(default)

def norm_date(s):
    """Seed uses both YYYY-MM-DD and DD-MM-YYYY; emit ISO or null."""
    s = str(s or '')
    for fmt in ('%Y-%m-%d', '%d-%m-%Y'):
        try:
            return q(datetime.datetime.strptime(s, fmt).strftime('%Y-%m-%d'))
        except ValueError:
            pass
    return 'null'

d = json.load(open(IN))
L = []
add = L.append
handled = set()

add('-- =====================================================================')
add('-- seed.sql — GENERATED by tools/convert-seed.py from firebase-seed.json')
add('-- Idempotent: safe to re-run (upserts / on-conflict-do-nothing).')
add('-- Run AFTER schema.sql.')
add('-- =====================================================================')
add('begin;')

# ---- solar ------------------------------------------------------------
if 'solar' in d:
    handled.add('solar')
    sol = d['solar']
    if 'meta' in sol:
        add(f"select set_module_state('solar/meta', {jq(sol['meta'])});")
    for itc_id, itc in (sol.get('itcs') or {}).items():
        rest = {k: v for k, v in itc.items() if k != 'acts'}
        add(f"insert into solar_itcs (id, data) values ({q(itc_id)}, {jq(rest)}) "
            f"on conflict (id) do update set data = excluded.data;")
        acts = itc.get('acts') or {}
        items = acts.items() if isinstance(acts, dict) else enumerate(acts)
        for idx, a in items:
            if a is None: continue
            known = {'done', 'today', 'subScope', 'subDone'}
            extra = {k: v for k, v in a.items() if k not in known}
            add("insert into solar_activities (itc_id, idx, done, today, sub_scope, sub_done, extra) values ("
                f"{q(itc_id)}, {int(idx)}, {num(a.get('done'))}, {num(a.get('today'))}, "
                f"{num(a['subScope']) if a.get('subScope') is not None else 'null'}, "
                f"{jq(a['subDone']) if a.get('subDone') is not None else 'null'}, {jq(extra)}) "
                "on conflict (itc_id, idx) do update set done=excluded.done, today=excluded.today, "
                "sub_scope=excluded.sub_scope, sub_done=excluded.sub_done, extra=excluded.extra;")
    for k in sol:
        if k not in ('meta', 'itcs'):
            add(f"select set_module_state({q('solar/' + k)}, {jq(sol[k])});")

# ---- wtg --------------------------------------------------------------
if 'wtg' in d:
    handled.add('wtg')
    w = d['wtg']
    if 'meta' in w:
        add(f"select set_module_state('wtg/meta', {jq(w['meta'])});")
    for tid, t in (w.get('turbines') or {}).items():
        add(f"insert into wtg_turbines (id, data) values ({q(tid)}, {jq(t)}) "
            f"on conflict (id) do update set data = excluded.data;")
    for k in w:
        if k not in ('meta', 'turbines'):
            add(f"select set_module_state({q('wtg/' + k)}, {jq(w[k])});")

# ---- bop --------------------------------------------------------------
def bop_act(section, key, val):
    add(f"insert into bop_activities (section, act_key, data) values "
        f"({q(section)}, {q(key)}, {jq(val)}) "
        f"on conflict (section, act_key) do update set data = excluded.data;")

def bop_asset(section, key, val):
    add(f"insert into bop_assets (section, asset_key, data) values "
        f"({q(section)}, {q(key)}, {jq(val)}) "
        f"on conflict (section, asset_key) do update set data = excluded.data;")

if 'bop' in d:
    handled.add('bop')
    b = d['bop']
    for k, v in (b.get('acts') or {}).items():   bop_act('33kv', k, v)
    for k, v in (b.get('acts66') or {}).items(): bop_act('66kv', k, v)
    for k, v in ((b.get('pss') or {}).get('acts') or {}).items(): bop_act('pss', k, v)
    for k, v in ((b.get('gss') or {}).get('acts') or {}).items(): bop_act('gss', k, v)
    f33 = b.get('feeders33') or []
    items = f33.items() if isinstance(f33, dict) else enumerate(f33)
    for i, v in items:
        if v is not None: bop_asset('feeders33', str(i), v)
    for k, v in (b.get('lines33') or {}).items(): bop_asset('lines33', k, v)
    for k, v in (b.get('poles33') or {}).items(): bop_asset('poles33', k, v)
    for k in b:
        if k not in ('acts', 'acts66', 'pss', 'gss', 'feeders33', 'lines33', 'poles33'):
            add(f"select set_module_state({q('bop/' + k)}, {jq(b[k])});")

# ---- rowIssues ---------------------------------------------------------
for key, r in (d.get('rowIssues') or {}).items():
    handled.add('rowIssues')
    add("insert into row_issues (legacy_id, loc, issue, type, status, opened, exp_clear, raised_by) values ("
        f"{q(key)}, {q(r.get('loc',''))}, {q(r.get('issue',''))}, "
        f"{q(r.get('type','Other'))}, {q(r.get('status','Open'))}, "
        f"{q(r.get('opened',''))}, {q(r.get('expClear',''))}, {q(r.get('raisedBy'))}) "
        "on conflict (legacy_id) do nothing;")

# ---- milestones ----------------------------------------------------------
for key, m in (d.get('milestones') or {}).items():
    handled.add('milestones')
    title = m.get('title') or m.get('label') or ''
    add("insert into milestones (legacy_id, title, mdate, mod) values ("
        f"{q(key)}, {q(title)}, {norm_date(m.get('date'))}, {q(m.get('mod','Overall'))}) "
        "on conflict (legacy_id) do nothing;")

# ---- hse ----------------------------------------------------------------
if 'hse' in d:
    handled.add('hse')
    KNOWN_OBS = {'type','severity','desc','area','loc','vendor','action',
                 'photoURL','closedBy','status','obs'}
    for key, o in (d['hse'].get('observations') or {}).items():
        extra = {k: v for k, v in o.items() if k not in KNOWN_OBS}
        add("insert into hse_observations (legacy_id, type, severity, description, obs, area, loc, "
            "vendor, action, photo_url, closed_by, status, extra) values ("
            f"{q(key)}, {q(o.get('type'))}, {q(o.get('severity'))}, {q(o.get('desc'))}, "
            f"{q(o.get('obs'))}, {q(o.get('area'))}, {q(o.get('loc'))}, {q(o.get('vendor'))}, "
            f"{q(o.get('action'))}, {q(o.get('photoURL') or o.get('photo') or None)}, "
            f"{q(o.get('closedBy'))}, {q(o.get('status','open'))}, {jq(extra)}) "
            "on conflict (legacy_id) do nothing;")
    for key, e in (d['hse'].get('employees') or {}).items():
        add("insert into hse_employees (legacy_id, code, name, score, photo) values ("
            f"{q(key)}, {q(e.get('code', key))}, {q(e.get('name',''))}, "
            f"{num(e.get('score'))}, {q(e.get('photo') or None)}) "
            "on conflict (legacy_id) do nothing;")

# ---- anything unhandled: preserve, loudly --------------------------------
for k in d:
    if k not in handled:
        print(f"WARNING: unmapped top-level node '{k}' preserved in module_state", file=sys.stderr)
        add(f"select set_module_state({q(k)}, {jq(d[k])});")

add('commit;')
open(OUT, 'w').write('\n'.join(L) + '\n')
print(f"wrote {OUT}: {len(L)} statements")
